# Generated by Django 2.2.26 on 2022-04-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
